- name: Install pygpgme and yum-utils
  yum: name={{ item }} state=present
  with_items:
    - pygpgme
    - yum-utils

- name: Assign Appcanary repository
  set_fact:
    yum_distro: fedora
  when: ansible_distribution == 'Fedora'

- name: Add Appcanary repository
  yum_repository:
    name: appcanary_agent
    description: Appcanary Agent Repository
    gpgkey: https://packagecloud.io/appcanary/agent/gpgkey
    repo_gpgcheck: yes
    gpgcheck: no
    baseurl: "https://packagecloud.io/appcanary/agent/{{yum_distro}}/$releasever/$basearch"
    enabled: yes

- name: Update yum package cache
  shell: yum -q makecache -y --disablerepo='*' --enablerepo='appcanary_agent'

- name: Install appcanary agent
  yum: name=appcanary state=present
