- name: Install pygpgme and yum-utils
  yum: name={{ item }} state=present
  with_items:
    - pygpgme
    - yum-utils

- name: Assign Appcanary repository
  set_fact:
    yum_distro: fedora
  when: ansible_distribution == 'Fedora'

- name: Add Appcanary repository
  template: src=yum_repo dest=/etc/yum.repos.d/appcanary_agent.repo owner=root group=root mode=0644

- name: Update yum package cache
  shell: yum -q makecache -y --disablerepo='*' --enablerepo='appcanary_agent'

- name: Install appcanary agent
  yum: name=appcanary state=present
